steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/${_TARGET_PROJECT_ID}/${_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '.'
    id: 'Build'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/${_TARGET_PROJECT_ID}/${_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
    id: 'Push'

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_LOCATION}-docker.pkg.dev/${_TARGET_PROJECT_ID}/${_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--port=8080'
      - '--execution-environment=gen2'
      - '--cpu=4'
      - '--memory=16Gi'
      - '--no-cpu-throttling'
      - '--gpu-type=nvidia-l4'
      - '--gpu=1'
      - '--no-gpu-zonal-redundancy'
      - '--service-account=${_SERVICE_ACCOUNT}'   
      - '--allow-unauthenticated'            
    id: 'Deploy'

# Define user-configurable variables
substitutions:
  _SERVICE_NAME: 'face-embedding-svc'
  _REPOSITORY: 'cloud-run-source-deploy' # e.g., 'ml-image'
  _LOCATION: 'asia-southeast2'
  _SERVICE_ACCOUNT: 'vertex-ai-svc@subsidi-tepat-bbm-ai-dev.iam.gserviceaccount.com' # e.g., 'my-service@project-id.iam.gserviceaccount.com'
  _TARGET_PROJECT_ID: 'subsidi-tepat-bbm-ai-dev'

# Store the built image in Artifact Registry
images:
  - '${_LOCATION}-docker.pkg.dev/${_TARGET_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'